name: Publish Generic Adapter

on:
  push:
    branches:
      - 'develop-lp'

jobs:
  detect-change:
    if: ${{ github.repository_owner  == 'linkpoolio' }}
    name: Detect Change
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Check whether generic adapter changed
        id: generic_adapter_change
        run: ./.github/scripts/isgenericadapterchange.sh

  build-and-publish:
    if: ${{ github.repository_owner  == 'linkpoolio' }}
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v2

      - name: Use Node.js '14'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Yarn Dependencies
        run: yarn

      - name: Setup Adapters
        run: yarn setup

      - name: Generate docker-compose File
        shell: bash
        run: yarn generate:docker-compose

      - name: Build Docker Image
        shell: bash
        run: docker-compose -f docker-compose.generated.yaml build generic-adapter

      - name: Login to Public ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Deploy Image
        run: |
          docker tag generic-adapter:$(docker image ls generic-adapter | awk '{print $2}' | tail -n +2) public.ecr.aws/${{ secrets.AWS_NAMESPACE }}/generic-adapter:latest
          docker push public.ecr.aws/${{ secrets.AWS_NAMESPACE }}/generic-adapter:latest
